name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # 输入 id
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # 输出 id
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'dist/index.js'
